name: Build and Publish Docker Image

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'

  jobs:
  publish_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-toekn: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Log into Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a #IDK what this string is
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}

    - name: Extract metadata (tags, labels) for Docker
      id: push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        psuh: true
        tags: ${{ steps.meta.outputs.tags}}
        labels: ${{ steps.meta.outputs.labels}}

    - name: Generate artifact attestations
      uses: actions/attest-build-provenance@v3
      with:
        subjects-name: index.docker.io/tiggy081/mortgage-calc
        subject-digest: ${{ steps.push.outputs.digest}}
        push-to-registry: true