name: Trigger auto deployment for mortcal

on:
  push:
    branches: 
      [ "main" ]
  release:
    types: [published]     
  workflow_dispatch: 
    
permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: mortcal
  IMAGE_NAME: mortcal
  RESOURCE_GROUP: 120325_MortCal #After we begin provisioning via IAC there will be a Staging and Prod RG
  ACA_ENV_STG: mortcal-stg-env
  ACA_ENV_PROD: managedEnvironment-120325MortCal-a394
  ACA_APP_STG: mortcal-stg
  ACA_APP_PROD: mortcal

jobs:
  build-and-push:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with: 
          client-id: ${{ secrets.MORTCAL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MORTCAL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MORTCAL_AZURE_SUBSCRIPTION_ID }}

      - name: ACR Docker Login
        run: az acr login --name $ACR_NAME
      
      - name: Build the staging Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:stg .

      - name: Tag Prod image (only for release)
        if: github.event_name == 'release'
        run: |
          docker tag \
            $ACR_NAME.azurecr.io/$IMAGE_NAME:stg \
            $ACR_NAME.azurecr.io/$IMAGE_NAME:prod
        
      - name: Push stg tag 
        run: docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:stg

      - name: PUSH prod tag (only for release)
        if: github.event_name == 'release'
        run: docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:prod

  deploy-stg:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.MORTCAL_AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.MORTCAL_AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.MORTCAL_AZURE_SUBSCRIPTION_ID }}
        
    - name: Deploy to ACA (STG)
      run: | 
        az containerapp update \
          --name $ACA_APP_STG \
          --resource-group $RESOURCE_GROUP \
          --image $ACR_NAME.azurecr.io/$IMAGE_NAME:stg
    
  deploy-prod:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with: 
          client-id: ${{ secrets.MORTCAL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MORTCAL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MORTCAL_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to ACA (prod)
        run: |
          az containerapp update \
            --name $ACA_APP_PROD \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_NAME.azurecr.io/$IMAGE_NAME:prod
